[project]
name = "chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio>=5.20.1",
    "numpy>=2.2.3",
    "pytest>=8.3.5",
    "regex>=2024.11.6",
    "torch>=2.6.0",
    "transformers>=4.49.0",
]
